### PR TITLE
ReapChildren handling and cleanup

### PR DESCRIPTION
**Pull request by deepikabhavnani**
Reap Children call handled 2 cases - 1 child process terminated 2. Child process killed using some signal
In event of both scenarios different event pipes were sent the information.

Changes:
Here we are scanning for all reasons the child process got terminated (Self / task done/ killed by signal) and performing further action in all the events.
1. SubmitEvent - an external event
2. RemoveTrackedProcessByPid
3. Internal event for notification

### CODE REVIEW

**Comment by cmonr** [comment]
@SenRamakri @edhemphill Thoughts on bringing this in for RC2?

**Comment by costanic** [comment]
@psppalash Do we need this?  I'm just going through old PRs and seeing if we can either close or merge.

**Comment by ryannowarm** [comment]
@psppalash , could this be part of your mem leak fix?

**Comment by psppalash** [comment]
@costanic @ryannowarm This is certainly not part of the mem leak fix. And I think these changes are not required right now.

**Comment by SenRamakri** [comment]
@costanic @psppalash @ryannowarm - I do remember that this change was the result of @deepikabhavnani's investigation on Meastro memory leak issue. Although this fix did not fix the original leak we were hunting I think this change would still be good candidate for a potential memory leak. I would suggest you re-review this PR before discarding.

**Comment by psppalash** [comment]
@SenRamakri I went through the code. These changes are not related to the memory leak. 
@deepikabhavnani 's made some changes in greasego and maestro which fixed some of the memory leaks. All her changes are already in master. I had verified this 3 weeks back.

**Comment by cmonr** [comment]
Going to close since PR's key components appear to already be a part of the codebase.

**Pull request closed without merging**
