### PR TITLE
Free the memory allocated by C.String and other modules

### PR DESCRIPTION
**Pull request by deepikabhavnani**

### CODE REVIEW

**Comment by SenRamakri** [comment]
@deepikabhavnani - Should these changes go into original greasego repo as well?

**Comment by deepikabhavnani** [comment]
> @deepikabhavnani - Should these changes go into original greasego repo as well?

https://github.com/armPelionEdge/greasego/pull/1

**Comment by cmonr** [comment]
@deepikabhavnani I thought the `build-deps.sh` script automatically pulls in the latest greasego version when building. Shouldn't the greasego PR only be needed?

**Comment by deepikabhavnani** [comment]
> I thought the build-deps.sh script automatically pulls in the latest greasego version when building

If that is the case, why do we need greasego source in vendor folder? We use the source in vendor and so not fetch it from git. Only gyp module is fetched.

https://github.com/armPelionEdge/maestro/blob/master/build-deps.sh#L37
 
>  I thought the build-deps.sh script automatically pulls in the latest greasego version when building

**Comment by cmonr** [comment]
> Only gyp module is fetched.
Ah, my mistake. I recalled some `git clone` happening and thought greasego was automatically being pulled/updated.

> If we put in dependency / SHA in script and fetch from repo directly it will be great, instead of maintaining multiple copies
One day...

At one point, it looked like this repo used godeps, but alas it's no longer used.

**Pull request merged**
