### PR TITLE
Fix bugs

### PR DESCRIPTION
**Pull request by psppalash**
- Replace hashmap with sync.Map everywhere in maestro
Bug fixes for the following tickets 
https://jira.arm.com/browse/PELEDGE19-1386?filter=-1
https://jira.arm.com/browse/PELEDGE19-1394?filter=-1
https://jira.arm.com/browse/PELEDGE19-1375?filter=-1

### CODE REVIEW

**Comment by psppalash** [comment]
Waiting for SQA team to verify the bug fixes.

DO NOT MERGE

**Comment by psppalash** [comment]
@mray190 Do you think this is because of my changes?
18 passing (6m)
  1 failing

  1) Maestro API
       DHCP
         should retrieve the active networking maestro config:
     Uncaught SyntaxError: Unexpected token c in JSON at position 0
      at JSON.parse (<anonymous>)
      at Context.<anonymous> (test.js:344:42)
      at Object.shell.exec.bind.ctx (commands.js:76:22)
      at /home/micray01/jenkins/workspace/maestro/tests/node_modules/shelljs/src/exec.js:127:9
      at ChildProcess.exithandler (child_process.js:301:5)
      at maybeClose (internal/child_process.js:970:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

**Comment by mray190** [comment]
rebuild

**Comment by mray190** [comment]
@psppalash I am rebuilding right now to check if it fails twice.

Our CI has been stable for about 2 weeks now. So the likelihood that it caught an actual bug is pretty high.

Additionally, looking through your code, the network manager is touched. The feature test that failed was related to the network manager. It it fails again, the code that is probably causing the failure is located within the network manager

**Comment by psppalash** [comment]
Thanks @mray190 . Looks like it failed again. I will have a look and see what could be going wrong.

**Comment by mray190** [comment]
To replicate the failure, run this command (while maestro is running):

```
sudo curl -XGET --unix-socket /tmp/maestroapi.sock http:/net/interfaces
```

**Comment by psppalash** [comment]
> To replicate the failure, run this command (while maestro is running):
> 
> ```
> sudo curl -XGET --unix-socket /tmp/maestroapi.sock http:/net/interfaces
> ```

@mray190 I could not replicate the failure using the above mentioned command. 
Additionally, I tried the same command with master branch and my branch, I get the same output (that is the same json object).

**Comment by mray190** [comment]
Rebased on dev and merged within PR #81

**Pull request closed without merging**
