### PR TITLE
DHCP client changes to reorder options/parameters and to add right options to discover packet

### PR DESCRIPTION
**Pull request by SenRamakri**
This PR adds additional options to discover packet and also re-orders options/parameters in ascending order. The reordering is not mandated by protocol but this does make debugging easier when we capture network trace. I have tested the changes and discover packet changes appears to be fixing the Dhcp NAK issue as well.

### CODE REVIEW

**Comment by edhemphill** [comment]
cool. Did you come up with these changes by looking at dhclient?

**Comment by SenRamakri** [comment]
@edhemphill - Yes, the changes are mostly based on network traffic captured from udhcpc client and looking into DHCP rfc.

**Comment by cmonr** [comment]
**Info:** This PR has now been rebased.

If this was made in error, feel free to force-push your local branch to restore the PR.

**Comment by cmonr** [comment]
Closing and reopening to see if the Travis CI updates get taken.

**Comment by cmonr** [comment]
Yas! CI changes finally took!

**Comment by SenRamakri** [comment]
CI ran and checks passed - kudos to @cmonr

**Pull request merged**
