### PR TITLE
Memory leak Fix

### PR DESCRIPTION
**Pull request by psppalash**
This PR fixes the Maestro memory Leak. Tested for 10 days on a Raspberry Pi. Also tested by India testing team.

### CODE REVIEW

**Comment by cmonr** [comment]
@mray190 Will this PR need https://github.com/armPelionEdge/maestro/pull/66/files before it can be properly tested?

Looks like the job failed against NPM.

**Comment by cmonr** [comment]
Let us know if the check ends up needing to be bypassed.

We have ways of forcing status checks if need be.

**Comment by psppalash** [comment]
@cmonr @mray190 Rebased on dev branch. One of the checks is still failing.

**Comment by mray190** [comment]
Waiting for Jenkins to re-run. Had to switch the target branch from `master` to `dev`.

When merging (assuming jenkins passes), let's squash all 3 commits into 1 commit

**Comment by psppalash** [comment]
> Waiting for Jenkins to re-run. Had to switch the target branch from `master` to `dev`.
> 
> When merging (assuming jenkins passes), let's squash all 3 commits into 1 commit

@mray190 Jenkins failed. Looks like npm error again.

**Comment by mray190** [comment]
@psppalash The error is not related to this ticket, and is a bug we are tracking in our backlog.

I will squash and merge!

**Pull request merged**
