### PR TITLE
vagrant: use host's gitconfig in vagrant

### PR DESCRIPTION
**Pull request by costanic**
this makes it easier to fetch and push to github from
within the Vagrant VM.

### CODE REVIEW

**Comment by CristianPrundeanuARM** [comment]
If you want to git push from within vagrant, you may want to also add the .ssh keys and config.

**Comment by costanic** [comment]
> If you want to git push from within vagrant, you may want to also add the .ssh keys and config.

I think the keys are already handled by lines 10-12.  Maybe we want to add the sshconfig too though?

**Comment by CristianPrundeanuARM** [comment]
You're right, the keys are already here. The config would add useful shortcuts like hostname/user defaults, but isn't super critical to have.

**Comment by johnmichaelwelsh** [comment]
Jenkins is PO'd because it doesn't have a default .gitconfig ??

**Comment by costanic** [comment]
Due to internal discussion, let's close this.  The purpose of the vagrant environment is limited to building and testing.  Development should occur on the host system.

**Pull request closed without merging**
