### PR TITLE
Elide use of M4 within the Go build process

### PR DESCRIPTION
**Pull request by theotherjimmy**
M4 was primarily used for:
 * Debug mode builds, where print statements are added to the code
 * Creating a generic thread safe Queue implementation

Without M4, the Go build tags and dead code elimination are used to 
switch out the implementation of the debug print statements, and all
instances of the Queue have been "un-genericified" so that they don't
rely on M4 for preprocessing. 

As far as I could measure, this does not affect performance or
executable size in any way. The debug builds are 24.3MiB before and
after this change and the release builds are 24.1MiB before and after.

### CODE REVIEW

**Comment by edhemphill** [comment]
@theotherjimmy  - could you also "de-preprocessor" this library using the same technique?
https://github.com/armPelionEdge/greasego

**Comment by theotherjimmy** [comment]
@edhemphill Yep. I'll do that and update the vendor copy in this repo following this PR.

**Comment by edhemphill** [comment]
ok - b/c this eliminates `src` i am going to get these other PRs in first, then will get this one in. Should have it done by COB

**Comment by edhemphill** [comment]
merged in manually

**Pull request closed without merging**
