### PR TITLE
changes for Edge Jenkins CI

### PR DESCRIPTION
**Pull request by sameer2209-arm**

### CODE REVIEW

**Comment by mohitsingalarm** [comment]
@mray190 : Kindly review the PR and feel free to add someone from your team for the same.

**Comment by sameer2209-arm** [comment]
@costanic @mray190 Created a multi-machine vagrant provisioning file which can provision a testing VM with previous configurations of your environment and also VMs for Jenkins build and Coverity purposes for our environments.

**Comment by costanic** [comment]
how is this used by the developer?  Does 'vagrant up' still work like previous? In other words, the following workflow should still work:
1. clone this repo
2. vagrant up
This should spin up a development environment.  Is that still how it works?

**Comment by sameer2209-arm** [comment]
> how is this used by the developer? Does 'vagrant up' still work like previous? In other words, the following workflow should still work:
> 
> 1. clone this repo
> 2. vagrant up
>    This should spin up a development environment.  Is that still how it works?

It has been set up in the way that **'vagrant up**' will bring up the VM with the development environment. If you need to spin up the VM with other environments just suffix vagrant up with the name of the environment. Example: **vagrant up jenkins_build** will spin up the VM with jenkins_build environment.

**Comment by sameer2209-arm** [comment]
> Doesn't work for vagrant-ssh:
> 
> ```
> ❯ vagrant ssh
> This command requires a specific VM name to target in a multi-VM environment.
> ~/workspace/maestro edge-jenkins-ci *8 ?11
> ```

Fixed it. 
Now **vagrant ssh** will sssh into the test environment VM.

**Comment by sameer2209-arm** [comment]
@mray190 Waiting for your review. Please review it.

**Pull request merged**
